FROM node:latest
WORKDIR /app
COPY . /app
EXPOSE 3000 4000 5000
ENV NODE_ENV=production
RUN npm install && apt-get update && apt-get install -y build-essential ca-certificates locales && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen && npm run build
USER root
CMD ["node", "server.js"]